### ISSUE TITLE
Set custom distributor not working in config.sh

### ISSUE THREAD

**Issue by metchebe** [sixsixfive/Hedera-icons#8]
Hi. I installed your icon theme in Debian (MATE) but the script was unable to set the custom distributor, after four changes the following error occurs:
`cp: cannot stat ‘logos/distributor-debian.png’: No such file or directory`

I worked around the problem using the following commands (also setting the menu icon):
`find . -type f -name distributor-debian.png -execdir cp -fv {} emblem-distributor.png \;`
`find . -type f -name distributor-debian.png -execdir cp -fv {} ../misc/start-here.png \;`

I hope this is useful. Regards.

**Comment by sixsixfive** [comment]
well I guess its fixed now, at least it works now in siduction/debian sid, devuan testing
